x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  user: "0:0"
  env_file:
    - .env
    - .env.mlflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__WEBSERVER__SECRET_KEY=mysecret
    - MLFLOW_TRACKING_URI=http://mlflow:5000
    - MLFLOW_DEFAULT_ARTIFACT_ROOT=/opt/airflow/mlflow_shared
    - MLFLOW_ARTIFACT_ROOT=/opt/airflow/mlflow_shared
    - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
    - AIRFLOW__SMTP__SMTP_PORT=587
    - AIRFLOW__SMTP__SMTP_USER=hamdanialhassangandi2020@gmail.com
    - AIRFLOW__SMTP__SMTP_PASSWORD=wjar apvg yica upmx
    - AIRFLOW__SMTP__SMTP_MAIL_FROM='ML Transport Accra <hamdanialhassangandi2020@gmail.com>'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./configs:/opt/airflow/configs
    - ./data:/opt/airflow/data
    - ./scripts:/opt/airflow/scripts
    - ./mlruns:/opt/airflow/mlruns
    - mlflow_data:/opt/airflow/mlflow_shared
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins /opt/airflow/mlruns /opt/airflow/mlflow_shared
        chown -R "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}" /opt/airflow/{logs,dags,plugins,mlruns}
        chmod -R 777 /opt/airflow/{logs,dags,plugins,mlruns,mlflow_shared}
        airflow db init && \
        airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --email admin@example.com \
          --role Admin \
          --password admin
    restart: on-failure

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    user: "0:0"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////data/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/data/artifacts
      - MLFLOW_ARTIFACT_ROOT=/data/artifacts
    command: >
      sh -c "mkdir -p /data/artifacts &&
             chmod -R 777 /data &&
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////data/mlflow.db --default-artifact-root /data/artifacts"
    volumes:
      - mlflow_data:/data
    ports:
      - "5000:5000"

volumes:
  postgres-db-volume:
  mlflow_data:
    driver: local
