# Model Configuration
model:
  name: "transport_predictor"
  version: "1.0.0"
  architecture: "transformer"
  params:
    learning_rate: 0.001
    batch_size: 64
    epochs: 100
    early_stopping_patience: 5
    validation_split: 0.2

# Data Paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  train_file: "data/processed/train.parquet"
  val_file: "data/processed/val.parquet"
  test_file: "data/processed/test.parquet"

# Feature Engineering
features:
  categorical_columns:
    - "route_id"
    - "stop_id"
    - "direction_id"
  numerical_columns:
    - "distance"
    - "speed"
    - "passenger_count"
  temporal_columns:
    - "timestamp"
    - "day_of_week"
    - "hour_of_day"

# Model Artifacts
artifacts:
  model_dir: "models"
  current_model: "models/current"
  archive_dir: "models/archive"
  mlflow:
    tracking_uri: "http://localhost:5000"
    experiment_name: "transport_optimization"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  cors_origins: ["*"]
  rate_limit: 100

# Monitoring
monitoring:
  enable_metrics: true
  prometheus_port: 9090
  grafana_port: 3000
  log_level: "INFO"
  performance_threshold:
    latency_ms: 100
    error_rate: 0.01

# A/B Testing
ab_testing:
  enabled: true
  traffic_split:
    control: 0.5
    treatment: 0.5
  minimum_sample_size: 1000
  significance_level: 0.05

# Model Evaluation
evaluation:
  metrics:
    - "mae"
    - "rmse"
    - "r2"
  threshold:
    mae: 5.0
    rmse: 7.0
    r2: 0.8

# Rollback Configuration
rollback:
  enable_auto_rollback: true
  performance_window: "1h"
  error_threshold: 0.05
  latency_threshold: 200

# MLflow Tracking
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  registry_uri: "sqlite:///mlflow.db"
  experiment_name: "transport_prediction"
  tags:
    environment: "development"
    team: "ml-engineering"

# Security
security:
  api_key_required: true
  ssl_enabled: true
  rate_limiting: true
  max_requests_per_minute: 100
