# Model Configuration
model:
  name: "transport_predictor"
  version: "1.0.0"
  architecture: "transformer"
  params:
    learning_rate: 0.001
    batch_size: 64
    epochs: 100
    early_stopping_patience: 5
    validation_split: 0.2
  artifacts_dir: "/opt/airflow/mlruns/models"

# Data Paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  models_dir: "models"
  train_file: "data/processed/train.parquet"
  val_file: "data/processed/val.parquet"
  test_file: "data/processed/test.parquet"

# Feature Engineering
features:
  categorical_columns:
    - "route_id"
    - "stop_id"
    - "direction_id"
  numerical_columns:
    - "distance"
    - "speed"
    - "passenger_count"
  temporal_columns:
    - "timestamp"
    - "day_of_week"
    - "hour_of_day"

# Model Artifacts
artifacts:
  model_dir: "models"
  current_model: "models/current"
  archive_dir: "models/archive"
  mlflow:
    tracking_uri: "sqlite:///mlflow.db"
    experiment_name: "transport_optimization"
    model_name: "transport_predictor"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  cors_origins: ["*"]
  rate_limit: 100
  debug: false

# Monitoring
monitoring:
  enable_metrics: true
  prometheus_port: 9090
  grafana_port: 3000
  log_level: "INFO"
  performance_threshold:
    latency_ms: 100
    error_rate: 0.01
  enable_prometheus: true
  health_check_interval: 30 # seconds

# A/B Testing
ab_testing:
  enabled: true
  traffic_split:
    control: 0.5
    treatment: 0.5
  minimum_sample_size: 1000
  significance_level: 0.05

# Model Evaluation
evaluation:
  metrics:
    - "mae"
    - "rmse"
    - "r2"
  threshold:
    mae: 5.0
    rmse: 7.0
    r2: 0.95

# Rollback Configuration
rollback:
  enable_auto_rollback: true
  performance_window: "1h"
  error_threshold: 0.05
  latency_threshold: 200

# MLflow Tracking
mlflow:
  tracking_uri: "http://mlflow:5000"
  registry_uri: "http://mlflow:5000"
  experiment_name: "Default"
  tags:
    environment: "development"
    team: "ml-engineering"

# Security
security:
  api_key_required: true
  ssl_enabled: true
  rate_limiting: true
  max_requests_per_minute: 100

# Route optimization settings
route_optimization:
  vehicle_capacity: 100
  max_route_time: 120 # minutes
  include_demand_estimation: true
  distance_calculation_method: "haversine"
  optimization_timeout: 300 # seconds

# Schedule optimization settings
schedule_optimization:
  vehicle_capacity: 100
  min_headway: 5 # minutes
  max_headway: 30 # minutes
  max_fleet_size: 50
  service_hours:
    start: 6 # 6 AM
    end: 22 # 10 PM
  time_periods:
    - "morning_peak"
    - "midday"
    - "afternoon_peak"
    - "evening"
    - "night"

# Demand prediction settings
demand_prediction:
  models:
    - "random_forest"
    - "xgboost"
    - "lightgbm"
    - "gradient_boosting"
  test_size: 0.2
  random_state: 42
  cross_validation_folds: 5
  feature_columns:
    - "hour"
    - "minute"
    - "time_of_day"
    - "time_period"
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"
    - "route_type_encoded"
    - "stop_sequence"
    - "stop_lat"
    - "stop_lon"

# Visualization settings
visualization:
  map_center: [5.5600, -0.2057] # Accra coordinates
  zoom_level: 11
  map_tiles: "OpenStreetMap"
  colors:
    major_stops: "red"
    medium_stops: "orange"
    regular_stops: "blue"
  chart_width: 1000
  chart_height: 600

# GTFS processing settings
gtfs:
  required_files:
    - "agency.txt"
    - "routes.txt"
    - "stops.txt"
    - "trips.txt"
    - "stop_times.txt"
    - "calendar.txt"
  optional_files:
    - "shapes.txt"
    - "fare_attributes.txt"
    - "fare_rules.txt"
  time_format: "%H:%M:%S"
  date_format: "%Y%m%d"

# Optimization constraints
constraints:
  max_route_distance: 50 # km
  min_route_distance: 1 # km
  max_stops_per_route: 50
  min_stops_per_route: 2
  max_travel_time: 120 # minutes
  min_travel_time: 5 # minutes

# Performance targets
targets:
  route_efficiency_improvement: 20 # percentage
  fleet_utilization_rate: 80 # percentage
  demand_prediction_accuracy: 85 # percentage
  schedule_optimization_time: 300 # seconds
  api_response_time: 2 # seconds
